/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

//
// AUTOGENERATED
// DO NOT MODIFY
//

// Robert uses snowy's pbpack, so it needs snowy's CRC
static const ResourceVersion SYSTEM_RESOURCE_VERSION = {
  .crc = 217382165,  // 0x0cf4fd15 (snowy's CRC)
  .timestamp = 0
};
