#!/bin/bash
# Regenerate expected test images from actual PBI files generated by failing tests

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Counter for stats
total=0
success=0
failed=0

echo "Regenerating test images from actual PBI files..."
echo ""

# Find all actual PBI files and process them
for actual_pbi in $(find build/test/tests/failed_* -name "*-actual.pbi" 2>/dev/null); do
    total=$((total + 1))

    # Extract the base filename (remove path and -actual.pbi suffix)
    basename=$(basename "$actual_pbi" -actual.pbi)

    # Output PBI files (in both tests/test_images/ and build/test/tests/test_images/)
    output_pbi_source="tests/test_images/${basename}.pbi"
    output_pbi_build="build/test/tests/test_images/${basename}.pbi"

    echo "[$total] Updating: $basename"

    # Copy actual PBI to both locations
    mkdir -p "$(dirname "$output_pbi_source")"
    mkdir -p "$(dirname "$output_pbi_build")"

    if cp "$actual_pbi" "$output_pbi_source" && cp "$actual_pbi" "$output_pbi_build"; then
        echo "    -> $output_pbi_source"
        echo "    -> $output_pbi_build"
        success=$((success + 1))
    else
        echo "    ERROR: Failed to copy $actual_pbi"
        failed=$((failed + 1))
    fi
done

echo ""
echo "================================================================"
echo "Regeneration complete!"
echo "  Total:   $total"
echo "  Success: $success"
echo "  Failed:  $failed"
echo "================================================================"
