// Generators for the files the SDK's waf configure step would produce:
// appinfo.json (from package.json), appinfo.auto.c, resource_ids.auto.*,
// message_keys.auto.*, and pebble_app.ld.auto. Templates mirror
// build/sdk/common/tools/generate_appinfo.py and the SDK waftools.

const AUTOGEN = '\n//\n// AUTOGENERATED BY BUILD\n// DO NOT MODIFY - CHANGES WILL BE OVERWRITTEN\n//\n';

// Per-platform build parameters, transcribed from the SDK's own
// table (build/sdk/common/tools/pebble_sdk_platform.py) so a board's
// defines cannot drift: without the right ones an app silently
// compiles the wrong layout variant. 'tags' also drives which of a
// resource's ~tagged variants a platform picks.
export const PLATFORMS = {
  aplite: {
    color: false,
    appMemory: 24576,
    maxGlyphSize: 256,
    defines: [
       'PBL_PLATFORM_APLITE', 'PBL_BW', 'PBL_RECT', 'PBL_COMPASS',
       'PBL_DISPLAY_WIDTH=144', 'PBL_DISPLAY_HEIGHT=168', 'PBL_SDK_FROZEN',
    ],
    tags: [
       'aplite', 'bw', 'rect', 'compass', '144w', '168h',
    ],
  },
  basalt: {
    color: true,
    appMemory: 65536,
    maxGlyphSize: 256,
    defines: [
       'PBL_PLATFORM_BASALT', 'PBL_COLOR', 'PBL_RECT', 'PBL_MICROPHONE',
       'PBL_SMARTSTRAP', 'PBL_HEALTH', 'PBL_COMPASS',
       'PBL_SMARTSTRAP_POWER', 'PBL_DISPLAY_WIDTH=144',
       'PBL_DISPLAY_HEIGHT=168', 'PBL_SDK_FROZEN',
    ],
    tags: [
       'basalt', 'color', 'rect', 'mic', 'strap', 'strappower', 'compass',
       'health', '144w', '168h',
    ],
  },
  chalk: {
    color: true,
    appMemory: 65536,
    maxGlyphSize: 256,
    defines: [
       'PBL_PLATFORM_CHALK', 'PBL_COLOR', 'PBL_ROUND', 'PBL_MICROPHONE',
       'PBL_SMARTSTRAP', 'PBL_HEALTH', 'PBL_COMPASS',
       'PBL_SMARTSTRAP_POWER', 'PBL_DISPLAY_WIDTH=180',
       'PBL_DISPLAY_HEIGHT=180', 'PBL_SDK_FROZEN',
    ],
    tags: [
       'chalk', 'color', 'round', 'mic', 'strap', 'strappower', 'compass',
       'health', '180w', '180h',
    ],
  },
  diorite: {
    color: false,
    appMemory: 65536,
    maxGlyphSize: 256,
    defines: [
       'PBL_PLATFORM_DIORITE', 'PBL_BW', 'PBL_RECT', 'PBL_MICROPHONE',
       'PBL_HEALTH', 'PBL_SMARTSTRAP', 'PBL_DISPLAY_WIDTH=144',
       'PBL_DISPLAY_HEIGHT=168', 'PBL_SDK_FROZEN',
    ],
    tags: [
       'diorite', 'bw', 'rect', 'mic', 'strap', 'health', '144w', '168h',
    ],
  },
  emery: {
    color: true,
    appMemory: 131072,
    maxGlyphSize: 512,
    defines: [
       'PBL_PLATFORM_EMERY', 'PBL_COLOR', 'PBL_RECT', 'PBL_MICROPHONE',
       'PBL_SMARTSTRAP', 'PBL_HEALTH', 'PBL_SMARTSTRAP_POWER',
       'PBL_COMPASS', 'PBL_TOUCH', 'PBL_RGB_BACKLIGHT', 'PBL_SPEAKER',
       'PBL_DISPLAY_WIDTH=200', 'PBL_DISPLAY_HEIGHT=228',
    ],
    tags: [
       'emery', 'color', 'rect', 'mic', 'strap', 'health', 'strappower',
       'compass', 'touch', 'speaker', '200w', '228h',
    ],
  },
  flint: {
    color: false,
    appMemory: 65536,
    maxGlyphSize: 256,
    defines: [
       'PBL_PLATFORM_FLINT', 'PBL_BW', 'PBL_RECT', 'PBL_MICROPHONE',
       'PBL_HEALTH', 'PBL_COMPASS', 'PBL_SPEAKER', 'PBL_DISPLAY_WIDTH=144',
       'PBL_DISPLAY_HEIGHT=168',
    ],
    tags: [
       'flint', 'bw', 'rect', 'mic', 'health', 'compass', 'speaker', '144w',
       '168h',
    ],
  },
  gabbro: {
    color: true,
    appMemory: 131072,
    maxGlyphSize: 512,
    defines: [
       'PBL_PLATFORM_GABBRO', 'PBL_COLOR', 'PBL_ROUND', 'PBL_MICROPHONE',
       'PBL_HEALTH', 'PBL_COMPASS', 'PBL_TOUCH', 'PBL_DISPLAY_WIDTH=260',
       'PBL_DISPLAY_HEIGHT=260',
    ],
    tags: [
       'gabbro', 'color', 'round', 'mic', 'health', 'compass', 'touch',
       '260w', '260h',
    ],
  },
};

// package.json (with .pebble) -> appinfo.json object, as the SDK does.
export function genAppinfoJson(pkg) {
  const p = pkg.pebble || {};
  const displayName = p.displayName || pkg.name || 'App';
  return {
    sdkVersion: p.sdkVersion || '3',
    projectType: p.projectType || 'native',
    uuid: p.uuid,
    messageKeys: p.messageKeys || {},
    enableMultiJS: p.enableMultiJS !== false,
    displayName,
    watchapp: {
      onlyShownOnCommunication: !!(p.watchapp && p.watchapp.onlyShownOnCommunication),
      hiddenApp: !!(p.watchapp && p.watchapp.hiddenApp),
      watchface: !!(p.watchapp && p.watchapp.watchface),
    },
    targetPlatforms: p.targetPlatforms || ['emery'],
    capabilities: p.capabilities || [],
    name: displayName,
    shortName: displayName,
    longName: displayName,
    versionLabel: pkg.version || '1.0',
    companyName: pkg.author
      ? (typeof pkg.author === 'string' ? pkg.author.split('<')[0].trim() : pkg.author.name)
      : 'Unknown',
    appKeys: normalizeMessageKeys(p.messageKeys),
    resources: p.resources || { media: [] },
  };
}

// messageKeys may be an object {NAME: n} or an array of names.
// An array of message keys is numbered from 10000. A key written
// NAME[n] is a "block" key: it reserves n consecutive ids under the bare
// name, and blocks are numbered before the single keys. Blocks are also
// kept out of appinfo.json, so PebbleKit JS never sees them
// (process_message_keys.py, and _write_appinfo_json_file).
export function messageKeysFor(mk) {
  if (!mk) return { all: {}, appKeys: {} };
  if (!Array.isArray(mk)) return { all: { ...mk }, appKeys: { ...mk } };
  const all = {};
  const blocks = [];
  let next = 10000;
  for (const entry of mk) {
    const m = /^(\w+)\[(\d+)\]$/.exec(entry);
    if (!m) continue;
    all[m[1]] = next;
    next += parseInt(m[2], 10);
    blocks.push(m[1]);
  }
  for (const entry of mk) {
    if (/\]$/.test(entry)) continue;
    all[entry] = next++;
  }
  const appKeys = { ...all };
  for (const b of blocks) delete appKeys[b];
  return { all, appKeys };
}

export function normalizeMessageKeys(mk) {
  return messageKeysFor(mk).appKeys;
}

export function genAppinfoC(appinfo, platform) {
  const uuidBytes = appinfo.uuid.replace(/-/g, '').match(/../g)
    .map((h) => '0x' + h.toUpperCase()).join(', ');
  const [maj = '0', min = '0'] = String(appinfo.versionLabel).split('.');
  const wa = appinfo.watchapp || {};
  const flags = [];
  if (wa.watchface) flags.push('PROCESS_INFO_WATCH_FACE');
  if (wa.onlyShownOnCommunication) flags.push('PROCESS_INFO_VISIBILITY_SHOWN_ON_COMMUNICATION');
  if (wa.hiddenApp) flags.push('PROCESS_INFO_VISIBILITY_HIDDEN');
  if (appinfo.projectType === 'moddable') flags.push('PROCESS_INFO_MODDABLE_APP');
  flags.push(`PROCESS_INFO_PLATFORM_${platform.toUpperCase()}`);

  let icon = 'DEFAULT_MENU_ICON';
  for (const r of (appinfo.resources && appinfo.resources.media) || []) {
    if (r.menuIcon) icon = 'RESOURCE_ID_' + r.name;
  }

  return `#include "pebble_process_info.h"
#include "src/resource_ids.auto.h"

const PebbleProcessInfo __pbl_app_info __attribute__ ((section (".pbl_header"))) = {
  .header = "PBLAPP",
  .struct_version = { PROCESS_INFO_CURRENT_STRUCT_VERSION_MAJOR, PROCESS_INFO_CURRENT_STRUCT_VERSION_MINOR },
  .sdk_version = { PROCESS_INFO_CURRENT_SDK_VERSION_MAJOR, PROCESS_INFO_CURRENT_SDK_VERSION_MINOR },
  .process_version = { ${parseInt(maj, 10)}, ${parseInt(min, 10)} },
  .load_size = 0xb6b6,
  .offset = 0xb6b6b6b6,
  .crc = 0xb6b6b6b6,
  .name = "${appinfo.shortName}",
  .company = "${appinfo.companyName}",
  .icon_resource_id = ${icon},
  .sym_table_addr = 0xA7A7A7A7,
  .flags = ${flags.join(' | ')},
  .num_reloc_entries = 0xdeadcafe,
  .uuid = { ${uuidBytes} },
  .virtual_size = 0xb6b6
};
`;
}

// resourceNames may be plain names or {name, aliases}. An alias is a
// second RESOURCE_ID for the same resource; publishedMedia adds
// PUBLISHED_ID_<name> constants used by app glances and the timeline
// (generate_resource_id_header.py).
function eachResourceId(resourceNames, publishedMedia, emit, emitPublished) {
  resourceNames.forEach((entry, i) => {
    const name = typeof entry === 'string' ? entry : entry.name;
    emit(name, i + 1);
    const aliases = (typeof entry === 'string' ? null : entry.aliases) || [];
    for (const a of aliases) emit(a, i + 1, true);
  });
  for (const item of publishedMedia || []) {
    if (item && item.name) emitPublished(item.name, item.id || 0);
  }
}

export function genResourceIdsH(resourceNames, publishedMedia) {
  let s = '#pragma once\n' + AUTOGEN + '\n#define  DEFAULT_MENU_ICON  0\n\n';
  eachResourceId(resourceNames, publishedMedia,
    (n, i, alias) => { s += `#define  RESOURCE_ID_${n}  ${i}` + (alias ? ' // alias\n' : '\n'); },
    (n, id) => { s += `#define  PUBLISHED_ID_${n}  ${id}\n`; });
  return s;
}

export function genResourceIdsC(resourceNames, publishedMedia) {
  let s = '#include <stdint.h>\n' + AUTOGEN + '\n';
  eachResourceId(resourceNames, publishedMedia,
    (n, i, alias) => { s += `uint32_t RESOURCE_ID_${n} = ${i};` + (alias ? ' // alias\n' : '\n'); },
    (n, id) => { s += `uint32_t PUBLISHED_ID_${n} = ${id};\n`; });
  return s;
}

export function genMessageKeysC(appKeys) {
  let s = '\n#include <stdint.h>\n' + AUTOGEN + '\n';
  for (const name of Object.keys(appKeys).sort()) {
    s += `uint32_t MESSAGE_KEY_${name} = ${appKeys[name]};\n`;
  }
  return s;
}

export function genMessageKeysH(appKeys) {
  let s = '#pragma once\n#include <stdint.h>\n' + AUTOGEN + '\n';
  for (const name of Object.keys(appKeys).sort()) {
    s += `extern uint32_t MESSAGE_KEY_${name};\n`;
  }
  return s;
}

export function genLdScript(platform) {
  const size = (PLATFORMS[platform] || {}).appMemory || 65536;
  return `
ENTRY(main)

MEMORY
{
  APP (rwx) : ORIGIN = 0, LENGTH = ${size}
}

SECTIONS
{
    .header :
    {
        KEEP(*(.pbl_header))

    } > APP

    /* -- DO NOT ADD ANY NEW SECTIONS HERE AND DO NOT CHANGE THE ALIGNMENT -- */
    /* The GNU build ID is tacked to the end of the PebbleProcessInfo struct: */
    .note.gnu.build-id ALIGN(1) : {
        PROVIDE(BUILD_ID = .);
        KEEP(*(.note.gnu.build-id))
    } > APP

    .text :
    {
        *(.text)
        *(.text.*)
        *(.rodata)
        *(.rodata*)
    } > APP

    .data :
    {
        KEEP(*(.data))
        *(.data.*)
    } > APP

    .bss :
    {
        *(.bss)
        *(.bss.*)
    } > APP

    DISCARD :
    {
        libc.a ( * )
        libm.a ( * )
        libgcc.a ( * )
        *(.eh_frame)
    }
}

/* vim:filetype=ld */
`;
}

// Platform compiler defines, mirroring the SDK's per-platform env.
// Kept as its own export for callers that only want the -D list.
export const PLATFORM_DEFINES = Object.fromEntries(
  Object.entries(PLATFORMS).map(([name, p]) => [name, p.defines]));
