// Generators for the files the SDK's waf configure step would produce:
// appinfo.json (from package.json), appinfo.auto.c, resource_ids.auto.*,
// message_keys.auto.*, and pebble_app.ld.auto. Templates mirror
// build/sdk/common/tools/generate_appinfo.py and the SDK waftools.

const AUTOGEN = '\n//\n// AUTOGENERATED BY BUILD\n// DO NOT MODIFY - CHANGES WILL BE OVERWRITTEN\n//\n';

// Per-platform build parameters, transcribed from the SDK's own
// table (build/sdk/common/tools/pebble_sdk_platform.py) so a board's
// defines cannot drift: without the right ones an app silently
// compiles the wrong layout variant.
export const PLATFORMS = {
  aplite: {
    color: false,
    appMemory: 24576,
    maxGlyphSize: 256,
    defines: [
      'PBL_PLATFORM_APLITE', 'PBL_BW', 'PBL_RECT', 'PBL_COMPASS',
      'PBL_DISPLAY_WIDTH=144', 'PBL_DISPLAY_HEIGHT=168', 'PBL_SDK_FROZEN',
    ],
  },
  basalt: {
    color: true,
    appMemory: 65536,
    maxGlyphSize: 256,
    defines: [
      'PBL_PLATFORM_BASALT', 'PBL_COLOR', 'PBL_RECT', 'PBL_MICROPHONE',
      'PBL_SMARTSTRAP', 'PBL_HEALTH', 'PBL_COMPASS',
      'PBL_SMARTSTRAP_POWER', 'PBL_DISPLAY_WIDTH=144',
      'PBL_DISPLAY_HEIGHT=168', 'PBL_SDK_FROZEN',
    ],
  },
  chalk: {
    color: true,
    appMemory: 65536,
    maxGlyphSize: 256,
    defines: [
      'PBL_PLATFORM_CHALK', 'PBL_COLOR', 'PBL_ROUND', 'PBL_MICROPHONE',
      'PBL_SMARTSTRAP', 'PBL_HEALTH', 'PBL_COMPASS',
      'PBL_SMARTSTRAP_POWER', 'PBL_DISPLAY_WIDTH=180',
      'PBL_DISPLAY_HEIGHT=180', 'PBL_SDK_FROZEN',
    ],
  },
  diorite: {
    color: false,
    appMemory: 65536,
    maxGlyphSize: 256,
    defines: [
      'PBL_PLATFORM_DIORITE', 'PBL_BW', 'PBL_RECT', 'PBL_MICROPHONE',
      'PBL_HEALTH', 'PBL_SMARTSTRAP', 'PBL_DISPLAY_WIDTH=144',
      'PBL_DISPLAY_HEIGHT=168', 'PBL_SDK_FROZEN',
    ],
  },
  emery: {
    color: true,
    appMemory: 131072,
    maxGlyphSize: 512,
    defines: [
      'PBL_PLATFORM_EMERY', 'PBL_COLOR', 'PBL_RECT', 'PBL_MICROPHONE',
      'PBL_SMARTSTRAP', 'PBL_HEALTH', 'PBL_SMARTSTRAP_POWER',
      'PBL_COMPASS', 'PBL_TOUCH', 'PBL_RGB_BACKLIGHT', 'PBL_SPEAKER',
      'PBL_DISPLAY_WIDTH=200', 'PBL_DISPLAY_HEIGHT=228',
    ],
  },
  flint: {
    color: false,
    appMemory: 65536,
    maxGlyphSize: 256,
    defines: [
      'PBL_PLATFORM_FLINT', 'PBL_BW', 'PBL_RECT', 'PBL_MICROPHONE',
      'PBL_HEALTH', 'PBL_COMPASS', 'PBL_SPEAKER', 'PBL_DISPLAY_WIDTH=144',
      'PBL_DISPLAY_HEIGHT=168',
    ],
  },
  gabbro: {
    color: true,
    appMemory: 131072,
    maxGlyphSize: 512,
    defines: [
      'PBL_PLATFORM_GABBRO', 'PBL_COLOR', 'PBL_ROUND', 'PBL_MICROPHONE',
      'PBL_HEALTH', 'PBL_COMPASS', 'PBL_TOUCH', 'PBL_DISPLAY_WIDTH=260',
      'PBL_DISPLAY_HEIGHT=260',
    ],
  },
};

// package.json (with .pebble) -> appinfo.json object, as the SDK does.
export function genAppinfoJson(pkg) {
  const p = pkg.pebble || {};
  const displayName = p.displayName || pkg.name || 'App';
  return {
    sdkVersion: p.sdkVersion || '3',
    projectType: p.projectType || 'native',
    uuid: p.uuid,
    messageKeys: p.messageKeys || {},
    enableMultiJS: p.enableMultiJS !== false,
    displayName,
    watchapp: {
      onlyShownOnCommunication: !!(p.watchapp && p.watchapp.onlyShownOnCommunication),
      hiddenApp: !!(p.watchapp && p.watchapp.hiddenApp),
      watchface: !!(p.watchapp && p.watchapp.watchface),
    },
    targetPlatforms: p.targetPlatforms || ['emery'],
    capabilities: p.capabilities || [],
    name: displayName,
    shortName: displayName,
    longName: displayName,
    versionLabel: pkg.version || '1.0',
    companyName: pkg.author
      ? (typeof pkg.author === 'string' ? pkg.author.split('<')[0].trim() : pkg.author.name)
      : 'Unknown',
    appKeys: normalizeMessageKeys(p.messageKeys),
    resources: p.resources || { media: [] },
  };
}

// messageKeys may be an object {NAME: n} or an array of names.
export function normalizeMessageKeys(mk) {
  if (!mk) return {};
  if (Array.isArray(mk)) {
    const out = {};
    let next = 10000;
    for (const name of mk) out[name] = next++;
    return out;
  }
  return mk;
}

export function genAppinfoC(appinfo, platform) {
  const uuidBytes = appinfo.uuid.replace(/-/g, '').match(/../g)
    .map((h) => '0x' + h.toUpperCase()).join(', ');
  const [maj = '0', min = '0'] = String(appinfo.versionLabel).split('.');
  const wa = appinfo.watchapp || {};
  const flags = [];
  if (wa.watchface) flags.push('PROCESS_INFO_WATCH_FACE');
  if (wa.onlyShownOnCommunication) flags.push('PROCESS_INFO_VISIBILITY_SHOWN_ON_COMMUNICATION');
  if (wa.hiddenApp) flags.push('PROCESS_INFO_VISIBILITY_HIDDEN');
  if (appinfo.projectType === 'moddable') flags.push('PROCESS_INFO_MODDABLE_APP');
  flags.push(`PROCESS_INFO_PLATFORM_${platform.toUpperCase()}`);

  let icon = 'DEFAULT_MENU_ICON';
  for (const r of (appinfo.resources && appinfo.resources.media) || []) {
    if (r.menuIcon) icon = 'RESOURCE_ID_' + r.name;
  }

  return `#include "pebble_process_info.h"
#include "src/resource_ids.auto.h"

const PebbleProcessInfo __pbl_app_info __attribute__ ((section (".pbl_header"))) = {
  .header = "PBLAPP",
  .struct_version = { PROCESS_INFO_CURRENT_STRUCT_VERSION_MAJOR, PROCESS_INFO_CURRENT_STRUCT_VERSION_MINOR },
  .sdk_version = { PROCESS_INFO_CURRENT_SDK_VERSION_MAJOR, PROCESS_INFO_CURRENT_SDK_VERSION_MINOR },
  .process_version = { ${parseInt(maj, 10)}, ${parseInt(min, 10)} },
  .load_size = 0xb6b6,
  .offset = 0xb6b6b6b6,
  .crc = 0xb6b6b6b6,
  .name = "${appinfo.shortName}",
  .company = "${appinfo.companyName}",
  .icon_resource_id = ${icon},
  .sym_table_addr = 0xA7A7A7A7,
  .flags = ${flags.join(' | ')},
  .num_reloc_entries = 0xdeadcafe,
  .uuid = { ${uuidBytes} },
  .virtual_size = 0xb6b6
};
`;
}

export function genResourceIdsH(resourceNames) {
  let s = '#pragma once\n' + AUTOGEN + '\n#define  DEFAULT_MENU_ICON  0\n\n';
  resourceNames.forEach((n, i) => { s += `#define  RESOURCE_ID_${n}  ${i + 1}\n`; });
  return s;
}

export function genResourceIdsC(resourceNames) {
  let s = '#include <stdint.h>\n' + AUTOGEN + '\n';
  resourceNames.forEach((n, i) => { s += `uint32_t RESOURCE_ID_${n} = ${i + 1};\n`; });
  return s;
}

export function genMessageKeysC(appKeys) {
  let s = '\n#include <stdint.h>\n' + AUTOGEN + '\n';
  for (const name of Object.keys(appKeys).sort()) {
    s += `uint32_t MESSAGE_KEY_${name} = ${appKeys[name]};\n`;
  }
  return s;
}

export function genMessageKeysH(appKeys) {
  let s = '#pragma once\n#include <stdint.h>\n' + AUTOGEN + '\n';
  for (const name of Object.keys(appKeys).sort()) {
    s += `extern uint32_t MESSAGE_KEY_${name};\n`;
  }
  return s;
}

export function genLdScript(platform) {
  const size = (PLATFORMS[platform] || {}).appMemory || 65536;
  return `
ENTRY(main)

MEMORY
{
  APP (rwx) : ORIGIN = 0, LENGTH = ${size}
}

SECTIONS
{
    .header :
    {
        KEEP(*(.pbl_header))

    } > APP

    /* -- DO NOT ADD ANY NEW SECTIONS HERE AND DO NOT CHANGE THE ALIGNMENT -- */
    /* The GNU build ID is tacked to the end of the PebbleProcessInfo struct: */
    .note.gnu.build-id ALIGN(1) : {
        PROVIDE(BUILD_ID = .);
        KEEP(*(.note.gnu.build-id))
    } > APP

    .text :
    {
        *(.text)
        *(.text.*)
        *(.rodata)
        *(.rodata*)
    } > APP

    .data :
    {
        KEEP(*(.data))
        *(.data.*)
    } > APP

    .bss :
    {
        *(.bss)
        *(.bss.*)
    } > APP

    DISCARD :
    {
        libc.a ( * )
        libm.a ( * )
        libgcc.a ( * )
        *(.eh_frame)
    }
}

/* vim:filetype=ld */
`;
}

// Platform compiler defines, mirroring the SDK's per-platform env.
// Kept as its own export for callers that only want the -D list.
export const PLATFORM_DEFINES = Object.fromEntries(
  Object.entries(PLATFORMS).map(([name, p]) => [name, p.defines]));
