/* SPDX-FileCopyrightText: 2024 Google LLC */
/* SPDX-License-Identifier: Apache-2.0 */

#pragma once

//
// AUTOGENERATED
// DO NOT MODIFY
//

static const ResourceVersion SYSTEM_RESOURCE_VERSION = {
  .crc = 217382165,  // 0x0cf4fd15 - content CRC (with RLE4-compressed GOTHIC_18_COMPRESSED)
  .timestamp = 0
};
