name: Lint C/Proto files

on:
  pull_request:

jobs:
  has-changes:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    outputs:
      should-build: steps.filter.outputs.src == 'true'
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            src:
              - ".github/workflows/lint-clang.yml"
              - ".clang-format*"
              - "**/*.c"
              - "**/*.h"
              - "**/*.proto"
  lint:
    needs: has-changes
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Rebase onto target branch
        uses: ./.github/actions/rebase

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: "22"
