# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    # Enable v70 direct heartbeat when Memfault is enabled
    memfault_val = getattr(conf.env, 'memfault', 0)
    conf.env.analytics_direct_heartbeat = bool(int(memfault_val)) if memfault_val else False
    if conf.env.analytics_direct_heartbeat:
        conf.msg('v70 direct heartbeat', 'enabled')


def build(bld):
    use = []
    sources = ['analytics.c']

    if bld.env.memfault:
        use.append('memfault_includes')
        sources.append('memfault/analytics_impl.c')
        bld.env.DEFINES.append('ANALYTICS_IMPL_MEMFAULT')

    if getattr(bld.env, 'analytics_direct_heartbeat', False):
        if not bld.env.memfault:
            bld.fatal('analytics_direct_heartbeat requires memfault to be enabled')
        sources.append('direct/heartbeat_v70.c')
        use.append('fw_includes')
        bld.env.DEFINES.append('ANALYTICS_DIRECT_HEARTBEAT')

    bld.stlib(
        source=sources,
        target='services_common_analytics',
        use=use
    )

    bld.env.SERVICES.append('services_common_analytics')