# SPDX-Copyright-Text: 2026 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

def configure(conf):
    pass


def build(bld):
    use = []
    sources = ['analytics.c']

    if bld.env.memfault:
        use.append('memfault_includes')
        sources.append('memfault/analytics_impl.c')
        bld.env.DEFINES.append('ANALYTICS_IMPL_MEMFAULT')

    if getattr(bld.env, 'analytics_direct_heartbeat', False):
        sources.append('direct/heartbeat_v70.c')
        bld.env.DEFINES.append('ANALYTICS_DIRECT_HEARTBEAT')

    bld.stlib(
        source=sources,
        target='services_common_analytics',
        use=use
    )

    bld.env.SERVICES.append('services_common_analytics')